/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry_login;
  GtkWidget *Entry_password;
  GtkWidget *label_login;
  GtkWidget *label_password;
  GtkWidget *label_verif;
  GtkWidget *button_ok;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label13;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry_login = gtk_entry_new ();
  gtk_widget_show (entry_login);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_login, 184, 32);
  gtk_widget_set_size_request (entry_login, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_login), 8226);

  Entry_password = gtk_entry_new ();
  gtk_widget_show (Entry_password);
  gtk_fixed_put (GTK_FIXED (fixed1), Entry_password, 192, 88);
  gtk_widget_set_size_request (Entry_password, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (Entry_password), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (Entry_password), 8226);

  label_login = gtk_label_new (_("login"));
  gtk_widget_show (label_login);
  gtk_fixed_put (GTK_FIXED (fixed1), label_login, 104, 40);
  gtk_widget_set_size_request (label_login, 64, 16);

  label_password = gtk_label_new (_("password"));
  gtk_widget_show (label_password);
  gtk_fixed_put (GTK_FIXED (fixed1), label_password, 80, 96);
  gtk_widget_set_size_request (label_password, 96, 16);

  label_verif = gtk_label_new ("");
  gtk_widget_show (label_verif);
  gtk_fixed_put (GTK_FIXED (fixed1), label_verif, 192, 144);
  gtk_widget_set_size_request (label_verif, 152, 40);

  button_ok = gtk_button_new ();
  gtk_widget_show (button_ok);
  gtk_fixed_put (GTK_FIXED (fixed1), button_ok, 168, 192);
  gtk_widget_set_size_request (button_ok, 66, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_ok), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("ok?"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox5), label13, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_ok, "clicked",
                    G_CALLBACK (on_button_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry_login, "entry_login");
  GLADE_HOOKUP_OBJECT (window1, Entry_password, "Entry_password");
  GLADE_HOOKUP_OBJECT (window1, label_login, "label_login");
  GLADE_HOOKUP_OBJECT (window1, label_password, "label_password");
  GLADE_HOOKUP_OBJECT (window1, label_verif, "label_verif");
  GLADE_HOOKUP_OBJECT (window1, button_ok, "button_ok");
  GLADE_HOOKUP_OBJECT (window1, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window1, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window1, image5, "image5");
  GLADE_HOOKUP_OBJECT (window1, label13, "label13");

  return window1;
}

GtkWidget*
create_menu_coach (void)
{
  GtkWidget *menu_coach;
  GtkWidget *fixed2;
  GtkWidget *button_urgence;
  GtkWidget *button_adherent;
  GtkWidget *button3;
  GtkWidget *button_profile_coach;

  menu_coach = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (menu_coach), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (menu_coach), fixed2);

  button_urgence = gtk_button_new_with_mnemonic (_("cas d'urgence"));
  gtk_widget_show (button_urgence);
  gtk_fixed_put (GTK_FIXED (fixed2), button_urgence, 40, 320);
  gtk_widget_set_size_request (button_urgence, 480, 45);

  button_adherent = gtk_button_new_with_mnemonic (_("les maladies et l'etat physique du menbre"));
  gtk_widget_show (button_adherent);
  gtk_fixed_put (GTK_FIXED (fixed2), button_adherent, 32, 208);
  gtk_widget_set_size_request (button_adherent, 488, 77);

  button3 = gtk_button_new_with_mnemonic (_("afficher votre seance pendant cette semainn"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 40, 64);
  gtk_widget_set_size_request (button3, 488, 120);

  button_profile_coach = gtk_button_new_with_mnemonic (_("mon profile"));
  gtk_widget_show (button_profile_coach);
  gtk_fixed_put (GTK_FIXED (fixed2), button_profile_coach, 32, 416);
  gtk_widget_set_size_request (button_profile_coach, 480, 48);

  g_signal_connect ((gpointer) button_urgence, "clicked",
                    G_CALLBACK (on_button_urgence_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_adherent, "clicked",
                    G_CALLBACK (on_button_adherent_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_profile_coach, "clicked",
                    G_CALLBACK (on_button_profile_coach_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (menu_coach, menu_coach, "menu_coach");
  GLADE_HOOKUP_OBJECT (menu_coach, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (menu_coach, button_urgence, "button_urgence");
  GLADE_HOOKUP_OBJECT (menu_coach, button_adherent, "button_adherent");
  GLADE_HOOKUP_OBJECT (menu_coach, button3, "button3");
  GLADE_HOOKUP_OBJECT (menu_coach, button_profile_coach, "button_profile_coach");

  return menu_coach;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed3;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *button1;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label14;
  GtkWidget *button_w2_vers_menu;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label15;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window2), fixed3);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed3), scrolledwindow1, 168, 104);
  gtk_widget_set_size_request (scrolledwindow1, 300, 300);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed3), button1, 32, 208);
  gtk_widget_set_size_request (button1, 96, 48);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button1), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox6), label14, FALSE, FALSE, 0);

  button_w2_vers_menu = gtk_button_new ();
  gtk_widget_show (button_w2_vers_menu);
  gtk_fixed_put (GTK_FIXED (fixed3), button_w2_vers_menu, 48, 336);
  gtk_widget_set_size_request (button_w2_vers_menu, 82, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_w2_vers_menu), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("return"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox7), label15, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_w2_vers_menu, "clicked",
                    G_CALLBACK (on_button_w2_vers_menu_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window2, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window2, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window2, button1, "button1");
  GLADE_HOOKUP_OBJECT (window2, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window2, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window2, image6, "image6");
  GLADE_HOOKUP_OBJECT (window2, label14, "label14");
  GLADE_HOOKUP_OBJECT (window2, button_w2_vers_menu, "button_w2_vers_menu");
  GLADE_HOOKUP_OBJECT (window2, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window2, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window2, image7, "image7");
  GLADE_HOOKUP_OBJECT (window2, label15, "label15");

  gtk_widget_grab_focus (button1);
  return window2;
}

GtkWidget*
create_window_ajout (void)
{
  GtkWidget *window_ajout;
  GtkWidget *fixed4;
  GtkWidget *label_date;
  GtkObject *spinbutton_cjour_adj;
  GtkWidget *spinbutton_cjour;
  GtkObject *spinbutton_cmois_adj;
  GtkWidget *spinbutton_cmois;
  GtkObject *spinbutton_canne_adj;
  GtkWidget *spinbutton_canne;
  GtkWidget *label_type;
  GtkWidget *label_seance;
  GtkWidget *combobox_periode;
  GtkWidget *combobox_type;
  GtkWidget *button_return3;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label16;
  GtkWidget *button_ajouter2;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label17;

  window_ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_ajout), _("window3"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window_ajout), fixed4);

  label_date = gtk_label_new (_("date"));
  gtk_widget_show (label_date);
  gtk_fixed_put (GTK_FIXED (fixed4), label_date, 88, 136);
  gtk_widget_set_size_request (label_date, 41, 17);

  spinbutton_cjour_adj = gtk_adjustment_new (1, 1, 30, 1, 10, 10);
  spinbutton_cjour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_cjour_adj), 1, 0);
  gtk_widget_show (spinbutton_cjour);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton_cjour, 160, 128);
  gtk_widget_set_size_request (spinbutton_cjour, 60, 27);

  spinbutton_cmois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_cmois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_cmois_adj), 1, 0);
  gtk_widget_show (spinbutton_cmois);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton_cmois, 240, 128);
  gtk_widget_set_size_request (spinbutton_cmois, 60, 27);

  spinbutton_canne_adj = gtk_adjustment_new (1, 2018, 2025, 1, 10, 10);
  spinbutton_canne = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_canne_adj), 1, 0);
  gtk_widget_show (spinbutton_canne);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton_canne, 320, 128);
  gtk_widget_set_size_request (spinbutton_canne, 60, 27);

  label_type = gtk_label_new (_("type"));
  gtk_widget_show (label_type);
  gtk_fixed_put (GTK_FIXED (fixed4), label_type, 104, 208);
  gtk_widget_set_size_request (label_type, 41, 17);

  label_seance = gtk_label_new (_("seance"));
  gtk_widget_show (label_seance);
  gtk_fixed_put (GTK_FIXED (fixed4), label_seance, 80, 56);
  gtk_widget_set_size_request (label_seance, 96, 16);

  combobox_periode = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_periode);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox_periode, 168, 48);
  gtk_widget_set_size_request (combobox_periode, 227, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_periode), _("8:00_vers_10:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_periode), _("10:00_vers_12:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_periode), _("14:00_vers_17:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_periode), _("17:00_vers_19:00"));

  combobox_type = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_type);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox_type, 157, 203);
  gtk_widget_set_size_request (combobox_type, 200, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_type), _("gymnastique "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_type), _("musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_type), _("fitnesse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_type), _("boxe"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_type), _("dance"));

  button_return3 = gtk_button_new ();
  gtk_widget_show (button_return3);
  gtk_fixed_put (GTK_FIXED (fixed4), button_return3, 128, 272);
  gtk_widget_set_size_request (button_return3, 80, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_return3), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("return"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox8), label16, FALSE, FALSE, 0);

  button_ajouter2 = gtk_button_new ();
  gtk_widget_show (button_ajouter2);
  gtk_fixed_put (GTK_FIXED (fixed4), button_ajouter2, 256, 272);
  gtk_widget_set_size_request (button_ajouter2, 96, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_ajouter2), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox9), label17, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_return3, "clicked",
                    G_CALLBACK (on_button_return3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter2, "clicked",
                    G_CALLBACK (on_button_ajouter2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_ajout, window_ajout, "window_ajout");
  GLADE_HOOKUP_OBJECT (window_ajout, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window_ajout, label_date, "label_date");
  GLADE_HOOKUP_OBJECT (window_ajout, spinbutton_cjour, "spinbutton_cjour");
  GLADE_HOOKUP_OBJECT (window_ajout, spinbutton_cmois, "spinbutton_cmois");
  GLADE_HOOKUP_OBJECT (window_ajout, spinbutton_canne, "spinbutton_canne");
  GLADE_HOOKUP_OBJECT (window_ajout, label_type, "label_type");
  GLADE_HOOKUP_OBJECT (window_ajout, label_seance, "label_seance");
  GLADE_HOOKUP_OBJECT (window_ajout, combobox_periode, "combobox_periode");
  GLADE_HOOKUP_OBJECT (window_ajout, combobox_type, "combobox_type");
  GLADE_HOOKUP_OBJECT (window_ajout, button_return3, "button_return3");
  GLADE_HOOKUP_OBJECT (window_ajout, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window_ajout, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window_ajout, image8, "image8");
  GLADE_HOOKUP_OBJECT (window_ajout, label16, "label16");
  GLADE_HOOKUP_OBJECT (window_ajout, button_ajouter2, "button_ajouter2");
  GLADE_HOOKUP_OBJECT (window_ajout, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window_ajout, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window_ajout, image9, "image9");
  GLADE_HOOKUP_OBJECT (window_ajout, label17, "label17");

  return window_ajout;
}

GtkWidget*
create_window_adherent (void)
{
  GtkWidget *window_adherent;
  GtkWidget *fixed5;
  GtkWidget *treeview2;
  GtkWidget *button_retour1;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label18;

  window_adherent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_adherent), _("votre adherent"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window_adherent), fixed5);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview2, 104, 80);
  gtk_widget_set_size_request (treeview2, 856, 344);

  button_retour1 = gtk_button_new ();
  gtk_widget_show (button_retour1);
  gtk_fixed_put (GTK_FIXED (fixed5), button_retour1, 496, 488);
  gtk_widget_set_size_request (button_retour1, 120, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_retour1), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("return"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox10), label18, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview2, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_retour1, "clicked",
                    G_CALLBACK (on_button_retour1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_adherent, window_adherent, "window_adherent");
  GLADE_HOOKUP_OBJECT (window_adherent, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window_adherent, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (window_adherent, button_retour1, "button_retour1");
  GLADE_HOOKUP_OBJECT (window_adherent, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window_adherent, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window_adherent, image10, "image10");
  GLADE_HOOKUP_OBJECT (window_adherent, label18, "label18");

  return window_adherent;
}

GtkWidget*
create_window_urgence (void)
{
  GtkWidget *window_urgence;
  GtkWidget *fixed6;
  GtkWidget *button_return2;
  GtkWidget *label1;
  GtkWidget *entry_cas_urgence;
  GtkWidget *button_cas_urgence;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label19;

  window_urgence = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_urgence), _("window4"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window_urgence), fixed6);

  button_return2 = gtk_button_new_with_mnemonic (_("return"));
  gtk_widget_show (button_return2);
  gtk_fixed_put (GTK_FIXED (fixed6), button_return2, 32, 352);
  gtk_widget_set_size_request (button_return2, 66, 29);

  label1 = gtk_label_new (_("what "));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed6), label1, 80, 96);
  gtk_widget_set_size_request (label1, 80, 40);

  entry_cas_urgence = gtk_entry_new ();
  gtk_widget_show (entry_cas_urgence);
  gtk_fixed_put (GTK_FIXED (fixed6), entry_cas_urgence, 168, 104);
  gtk_widget_set_size_request (entry_cas_urgence, 264, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cas_urgence), 8226);

  button_cas_urgence = gtk_button_new ();
  gtk_widget_show (button_cas_urgence);
  gtk_fixed_put (GTK_FIXED (fixed6), button_cas_urgence, 384, 344);
  gtk_widget_set_size_request (button_cas_urgence, 66, 29);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_cas_urgence), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox11), label19, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_return2, "clicked",
                    G_CALLBACK (on_button_return2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_cas_urgence, "clicked",
                    G_CALLBACK (on_button_cas_urgence_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_urgence, window_urgence, "window_urgence");
  GLADE_HOOKUP_OBJECT (window_urgence, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window_urgence, button_return2, "button_return2");
  GLADE_HOOKUP_OBJECT (window_urgence, label1, "label1");
  GLADE_HOOKUP_OBJECT (window_urgence, entry_cas_urgence, "entry_cas_urgence");
  GLADE_HOOKUP_OBJECT (window_urgence, button_cas_urgence, "button_cas_urgence");
  GLADE_HOOKUP_OBJECT (window_urgence, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window_urgence, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window_urgence, image11, "image11");
  GLADE_HOOKUP_OBJECT (window_urgence, label19, "label19");

  return window_urgence;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed7;
  GtkWidget *fixed8;
  GtkWidget *label_seance0;
  GtkWidget *label_date0;
  GtkWidget *label_type;
  GtkWidget *entry_seance;
  GtkWidget *entry_date;
  GtkWidget *entry_type;
  GtkWidget *button_return_w3_vers_wa;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label20;
  GtkWidget *button5;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label21;
  GtkWidget *button_supprimer;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label22;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("window3"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window3), fixed7);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_fixed_put (GTK_FIXED (fixed7), fixed8, 344, 88);
  gtk_widget_set_size_request (fixed8, 50, 50);

  label_seance0 = gtk_label_new (_("seance"));
  gtk_widget_show (label_seance0);
  gtk_fixed_put (GTK_FIXED (fixed7), label_seance0, 72, 48);
  gtk_widget_set_size_request (label_seance0, 80, 16);

  label_date0 = gtk_label_new (_("date"));
  gtk_widget_show (label_date0);
  gtk_fixed_put (GTK_FIXED (fixed7), label_date0, 96, 88);
  gtk_widget_set_size_request (label_date0, 41, 17);

  label_type = gtk_label_new (_("type"));
  gtk_widget_show (label_type);
  gtk_fixed_put (GTK_FIXED (fixed7), label_type, 104, 144);
  gtk_widget_set_size_request (label_type, 41, 17);

  entry_seance = gtk_entry_new ();
  gtk_widget_show (entry_seance);
  gtk_fixed_put (GTK_FIXED (fixed7), entry_seance, 240, 48);
  gtk_widget_set_size_request (entry_seance, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_seance), 8226);

  entry_date = gtk_entry_new ();
  gtk_widget_show (entry_date);
  gtk_fixed_put (GTK_FIXED (fixed7), entry_date, 248, 96);
  gtk_widget_set_size_request (entry_date, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_date), 8226);

  entry_type = gtk_entry_new ();
  gtk_widget_show (entry_type);
  gtk_fixed_put (GTK_FIXED (fixed7), entry_type, 240, 144);
  gtk_widget_set_size_request (entry_type, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_type), 8226);

  button_return_w3_vers_wa = gtk_button_new ();
  gtk_widget_show (button_return_w3_vers_wa);
  gtk_fixed_put (GTK_FIXED (fixed7), button_return_w3_vers_wa, 88, 208);
  gtk_widget_set_size_request (button_return_w3_vers_wa, 66, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button_return_w3_vers_wa), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("return"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox12), label20, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed7), button5, 184, 208);
  gtk_widget_set_size_request (button5, 90, 29);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button5), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox13), label21, FALSE, FALSE, 0);

  button_supprimer = gtk_button_new ();
  gtk_widget_show (button_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed7), button_supprimer, 296, 208);
  gtk_widget_set_size_request (button_supprimer, 104, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_supprimer), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox14), label22, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_return_w3_vers_wa, "clicked",
                    G_CALLBACK (on_button_return_w3_vers_wa_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer, "clicked",
                    G_CALLBACK (on_button_supprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window3, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window3, label_seance0, "label_seance0");
  GLADE_HOOKUP_OBJECT (window3, label_date0, "label_date0");
  GLADE_HOOKUP_OBJECT (window3, label_type, "label_type");
  GLADE_HOOKUP_OBJECT (window3, entry_seance, "entry_seance");
  GLADE_HOOKUP_OBJECT (window3, entry_date, "entry_date");
  GLADE_HOOKUP_OBJECT (window3, entry_type, "entry_type");
  GLADE_HOOKUP_OBJECT (window3, button_return_w3_vers_wa, "button_return_w3_vers_wa");
  GLADE_HOOKUP_OBJECT (window3, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window3, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window3, image12, "image12");
  GLADE_HOOKUP_OBJECT (window3, label20, "label20");
  GLADE_HOOKUP_OBJECT (window3, button5, "button5");
  GLADE_HOOKUP_OBJECT (window3, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window3, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window3, image13, "image13");
  GLADE_HOOKUP_OBJECT (window3, label21, "label21");
  GLADE_HOOKUP_OBJECT (window3, button_supprimer, "button_supprimer");
  GLADE_HOOKUP_OBJECT (window3, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window3, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window3, image14, "image14");
  GLADE_HOOKUP_OBJECT (window3, label22, "label22");

  return window3;
}

GtkWidget*
create_window_mon_profile_coach (void)
{
  GtkWidget *window_mon_profile_coach;
  GtkWidget *fixed9;
  GtkWidget *entry_nom_coach;
  GtkWidget *entry_prenom_coach;
  GtkWidget *entry_email_coach;
  GtkWidget *entry_specialite_coach;
  GtkWidget *label_nom00;
  GtkWidget *label_prenom00;
  GtkWidget *label_email;
  GtkWidget *label000;
  GtkWidget *entry_page_facebook;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *entry_numero_coach;
  GtkWidget *button_modifier_coach;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label9;
  GtkWidget *button_return_vers_menu;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label8;

  window_mon_profile_coach = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_mon_profile_coach), _("Mon profile"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (window_mon_profile_coach), fixed9);

  entry_nom_coach = gtk_entry_new ();
  gtk_widget_show (entry_nom_coach);
  gtk_fixed_put (GTK_FIXED (fixed9), entry_nom_coach, 312, 24);
  gtk_widget_set_size_request (entry_nom_coach, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom_coach), 8226);

  entry_prenom_coach = gtk_entry_new ();
  gtk_widget_show (entry_prenom_coach);
  gtk_fixed_put (GTK_FIXED (fixed9), entry_prenom_coach, 320, 80);
  gtk_widget_set_size_request (entry_prenom_coach, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom_coach), 8226);

  entry_email_coach = gtk_entry_new ();
  gtk_widget_show (entry_email_coach);
  gtk_fixed_put (GTK_FIXED (fixed9), entry_email_coach, 320, 128);
  gtk_widget_set_size_request (entry_email_coach, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_email_coach), 8226);

  entry_specialite_coach = gtk_entry_new ();
  gtk_widget_show (entry_specialite_coach);
  gtk_fixed_put (GTK_FIXED (fixed9), entry_specialite_coach, 328, 192);
  gtk_widget_set_size_request (entry_specialite_coach, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_specialite_coach), 8226);

  label_nom00 = gtk_label_new (_("Nom"));
  gtk_widget_show (label_nom00);
  gtk_fixed_put (GTK_FIXED (fixed9), label_nom00, 208, 24);
  gtk_widget_set_size_request (label_nom00, 64, 32);

  label_prenom00 = gtk_label_new (_("prenom"));
  gtk_widget_show (label_prenom00);
  gtk_fixed_put (GTK_FIXED (fixed9), label_prenom00, 208, 72);
  gtk_widget_set_size_request (label_prenom00, 65, 40);

  label_email = gtk_label_new (_("E-mail"));
  gtk_widget_show (label_email);
  gtk_fixed_put (GTK_FIXED (fixed9), label_email, 208, 128);
  gtk_widget_set_size_request (label_email, 64, 24);

  label000 = gtk_label_new (_("Specialite"));
  gtk_widget_show (label000);
  gtk_fixed_put (GTK_FIXED (fixed9), label000, 208, 184);
  gtk_widget_set_size_request (label000, 80, 32);

  entry_page_facebook = gtk_entry_new ();
  gtk_widget_show (entry_page_facebook);
  gtk_fixed_put (GTK_FIXED (fixed9), entry_page_facebook, 320, 256);
  gtk_widget_set_size_request (entry_page_facebook, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_page_facebook), 8226);

  label6 = gtk_label_new (_("page Facebook"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed9), label6, 184, 256);
  gtk_widget_set_size_request (label6, 120, 24);

  label7 = gtk_label_new (_("numero"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed9), label7, 200, 312);
  gtk_widget_set_size_request (label7, 80, 24);

  entry_numero_coach = gtk_entry_new ();
  gtk_widget_show (entry_numero_coach);
  gtk_fixed_put (GTK_FIXED (fixed9), entry_numero_coach, 312, 304);
  gtk_widget_set_size_request (entry_numero_coach, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_numero_coach), 8226);

  button_modifier_coach = gtk_button_new ();
  gtk_widget_show (button_modifier_coach);
  gtk_fixed_put (GTK_FIXED (fixed9), button_modifier_coach, 312, 408);
  gtk_widget_set_size_request (button_modifier_coach, 144, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_modifier_coach), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox2), label9, FALSE, FALSE, 0);

  button_return_vers_menu = gtk_button_new ();
  gtk_widget_show (button_return_vers_menu);
  gtk_fixed_put (GTK_FIXED (fixed9), button_return_vers_menu, 48, 408);
  gtk_widget_set_size_request (button_return_vers_menu, 82, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button_return_vers_menu), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("return"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox1), label8, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_modifier_coach, "clicked",
                    G_CALLBACK (on_button_modifier_coach_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_return_vers_menu, "clicked",
                    G_CALLBACK (on_button_return_vers_menu_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_mon_profile_coach, window_mon_profile_coach, "window_mon_profile_coach");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, entry_nom_coach, "entry_nom_coach");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, entry_prenom_coach, "entry_prenom_coach");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, entry_email_coach, "entry_email_coach");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, entry_specialite_coach, "entry_specialite_coach");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, label_nom00, "label_nom00");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, label_prenom00, "label_prenom00");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, label_email, "label_email");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, label000, "label000");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, entry_page_facebook, "entry_page_facebook");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, label6, "label6");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, label7, "label7");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, entry_numero_coach, "entry_numero_coach");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, button_modifier_coach, "button_modifier_coach");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, image2, "image2");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, label9, "label9");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, button_return_vers_menu, "button_return_vers_menu");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, image1, "image1");
  GLADE_HOOKUP_OBJECT (window_mon_profile_coach, label8, "label8");

  return window_mon_profile_coach;
}

GtkWidget*
create_window_poid_ideal (void)
{
  GtkWidget *window_poid_ideal;
  GtkWidget *fixed10;
  GtkWidget *label10;
  GtkWidget *entry_poid_ideal;
  GtkWidget *button_ajout_poid_ideal;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label12;
  GtkWidget *button_poid_ideal;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label11;

  window_poid_ideal = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_poid_ideal), _("window4"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (window_poid_ideal), fixed10);

  label10 = gtk_label_new (_("Quel est le nombre \nde seance pour \nattendre un poid\n ideal"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed10), label10, 16, 80);
  gtk_widget_set_size_request (label10, 224, 112);

  entry_poid_ideal = gtk_entry_new ();
  gtk_widget_show (entry_poid_ideal);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_poid_ideal, 200, 112);
  gtk_widget_set_size_request (entry_poid_ideal, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_poid_ideal), 8226);

  button_ajout_poid_ideal = gtk_button_new ();
  gtk_widget_show (button_ajout_poid_ideal);
  gtk_fixed_put (GTK_FIXED (fixed10), button_ajout_poid_ideal, 240, 248);
  gtk_widget_set_size_request (button_ajout_poid_ideal, 90, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_ajout_poid_ideal), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox4), label12, FALSE, FALSE, 0);

  button_poid_ideal = gtk_button_new ();
  gtk_widget_show (button_poid_ideal);
  gtk_fixed_put (GTK_FIXED (fixed10), button_poid_ideal, 40, 248);
  gtk_widget_set_size_request (button_poid_ideal, 104, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_poid_ideal), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("return"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox3), label11, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_ajout_poid_ideal, "clicked",
                    G_CALLBACK (on_button_ajout_poid_ideal_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_poid_ideal, "clicked",
                    G_CALLBACK (on_button_poid_ideal_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_poid_ideal, window_poid_ideal, "window_poid_ideal");
  GLADE_HOOKUP_OBJECT (window_poid_ideal, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window_poid_ideal, label10, "label10");
  GLADE_HOOKUP_OBJECT (window_poid_ideal, entry_poid_ideal, "entry_poid_ideal");
  GLADE_HOOKUP_OBJECT (window_poid_ideal, button_ajout_poid_ideal, "button_ajout_poid_ideal");
  GLADE_HOOKUP_OBJECT (window_poid_ideal, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window_poid_ideal, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window_poid_ideal, image4, "image4");
  GLADE_HOOKUP_OBJECT (window_poid_ideal, label12, "label12");
  GLADE_HOOKUP_OBJECT (window_poid_ideal, button_poid_ideal, "button_poid_ideal");
  GLADE_HOOKUP_OBJECT (window_poid_ideal, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window_poid_ideal, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window_poid_ideal, image3, "image3");
  GLADE_HOOKUP_OBJECT (window_poid_ideal, label11, "label11");

  return window_poid_ideal;
}

